package test.erdemo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** name. */
	private String name;

	/** password. */
	private String password;

	/** The set of published_item. */
	private Set<PublishedItem> publishedItemSet;

	/**
	 * Constructor.
	 */
	public User() {
		this.publishedItemSet = new HashSet<PublishedItem>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the set of the published_item.
	 * 
	 * @param publishedItemSet
	 *            The set of published_item
	 */
	public void setPublishedItemSet(Set<PublishedItem> publishedItemSet) {
		this.publishedItemSet = publishedItemSet;
	}

	/**
	 * Add the published_item.
	 * 
	 * @param publishedItem
	 *            published_item
	 */
	public void addPublishedItem(PublishedItem publishedItem) {
		this.publishedItemSet.add(publishedItem);
	}

	/**
	 * Get the set of the published_item.
	 * 
	 * @return The set of published_item
	 */
	public Set<PublishedItem> getPublishedItemSet() {
		return this.publishedItemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
